spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cadastros
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
  main:
    allow-bean-definition-overriding: true
server:
  compression:
    enabled: true
tjf:
  api:
    filter:
      fields:
        enabled: true
